version: '3'

services:
  selenoid:
    container_name: selenoid
    network_mode: bridge
    ports:
      - "4444:4444"
    image: aerokube/selenoid:latest-release
    volumes:
      - "$PWD:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: [
      "-conf", "/etc/selenoid/browsers.json",
      "-service-startup-timeout", "3m0s", 
      "-session-attempt-timeout", "3m0s", 
      "-session-delete-timeout", "3m0s", 
      "-timeout", "5m0s"
      ]

  selenoid-ui:
    container_name: selenoid-ui
    network_mode: bridge
    ports:
      - "8081:8080"
    image: aerokube/selenoid-ui:latest-release
    command: [
      "--selenoid-uri", "http://selenoid:4444"
      ]
    depends_on:
      - selenoid
    links:
      - selenoid

  jenkins:
    container_name: jenkins
    network_mode: bridge
    ports:
      - 8080:8080
      - 50000:50000
    image: jenkins/jenkins
    user: root
    volumes:
      - $PWD/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - selenoid
    links:
      - selenoid