version: "3.7"

networks:
  selenoid-net:
    name: selenoid-net

services:
  jenkins:
    container_name: jenkins
    ports:
      - 8080:8080
      - 50000:50000
    image: jenkins/jenkins
    user: root
    volumes:
      - $PWD/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - selenoid-net

  selenoid:
    container_name: jenkins-selenoid
    ports:
      - 4445:4444
    image: aerokube/selenoid:latest-release
    volumes:
      - "$PWD:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: [
      "-conf", "/etc/selenoid/browsers.json",
      "-service-startup-timeout", "3m0s", 
      "-session-attempt-timeout", "3m0s", 
      "-session-delete-timeout", "3m0s", 
      "-timeout", "5m0s",
      "-container-network", "selenoid-net"
      ]
    depends_on:
      - jenkins
    networks:
      - selenoid-net

  selenoid-ui:
    container_name: jenkins-selenoid-ui
    ports:
      - 8082:8080
    image: aerokube/selenoid-ui:latest-release
    command: [
      "--selenoid-uri", "http://selenoid:4444"
      ]
    depends_on:
      - selenoid
    networks:
      - selenoid-net